language: ruby

cache: bundler

services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database eventaservo_test;' -U postgres

bundler_args: --without production --jobs=3 --retry=3
